services:
  # 1. Database SQL Server
  nexus-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nexus_db
    user: root
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!@#
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql/data # Sửa: Dùng named volume để tránh lỗi quyền hạn

  # 2. Backend API
  nexus-api:
    build:
      context: ./backend/Nexus
      dockerfile: Dockerfile
    container_name: nexus_api
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=nexus-db;Database=NexusERP;User Id=sa;Password=Password123!@#;TrustServerCertificate=True;
      - RedisConnection=nexus-redis:6379 # Sửa: Thêm dấu gạch ngang (-) ở đây
    depends_on:
      - nexus-db
      - nexus-redis # Sửa: API cần đợi cả Redis nữa

  # 3. Frontend Web
  nexus-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexus_web
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - nexus-api

  # 4. Redis (Sửa: Đưa ra ngoài cho thẳng hàng với các service khác)
  nexus-redis:
    image: redis:alpine
    container_name: nexus_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data # Sửa: Map volume để giữ cache khi restart

volumes:
  sqlvolume:
  redisdata:
