// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.API.Data;

#nullable disable

namespace Nexus.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus.API.Models.InventoryStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryStocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductDetailId = 1,
                            Quantity = 100,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductDetailId = 1,
                            Quantity = 900,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProductDetailId = 3,
                            Quantity = 5,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 4,
                            ProductDetailId = 3,
                            Quantity = 45,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 5,
                            ProductDetailId = 7,
                            Quantity = 200,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 6,
                            ProductDetailId = 7,
                            Quantity = 300,
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            CurrentBalance = 0m,
                            Name = "Công Ty Vinamilk",
                            Type = "Supplier"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hồ Chí Minh",
                            CurrentBalance = 0m,
                            Name = "Masan Consumer",
                            Type = "Supplier"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Củ Chi",
                            CurrentBalance = 0m,
                            Name = "Unilever Việt Nam",
                            Type = "Supplier"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bình Dương",
                            CurrentBalance = 0m,
                            Name = "Acecook Việt Nam",
                            Type = "Supplier"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Hà Nội",
                            CurrentBalance = 0m,
                            Name = "Coca-Cola VN",
                            Type = "Supplier"
                        },
                        new
                        {
                            Id = 6,
                            Address = "N/A",
                            CurrentBalance = 0m,
                            Name = "Khách Lẻ Vãng Lai",
                            Type = "Customer"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Khu Tập Thể A1",
                            CurrentBalance = 0m,
                            Name = "Chị Lan (Thành viên Vàng)",
                            Type = "Customer"
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PartnerId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Nexus.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Thực Phẩm Khô",
                            Name = "Mì Ăn Liền"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Đồ Uống",
                            Name = "Sữa Tươi Tiệt Trùng"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Đồ Uống",
                            Name = "Nước Ngọt Có Gas"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Hóa Phẩm",
                            Name = "Dầu Gội Đầu"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Gia Vị",
                            Name = "Nước Mắm"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Bánh Kẹo",
                            Name = "Bánh Snack"
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "8934561",
                            ImportPrice = 3500m,
                            ProductId = 1,
                            ProductName = "Mì Hảo Hảo Tôm Chua Cay",
                            SalePrice = 4500m,
                            Thumbnail = "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841",
                            Unit = "Gói"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "8934562",
                            ImportPrice = 7000m,
                            ProductId = 1,
                            ProductName = "Mì Omachi Sườn Hầm Ngũ Quả",
                            SalePrice = 8500m,
                            Thumbnail = "https://images.unsplash.com/photo-1591814468924-caf88d1232e1",
                            Unit = "Gói"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "8934563",
                            ImportPrice = 100000m,
                            ProductId = 1,
                            ProductName = "Thùng Mì Hảo Hảo (30 Gói)",
                            SalePrice = 125000m,
                            Unit = "Thùng"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "8931111",
                            ImportPrice = 7000m,
                            ProductId = 2,
                            ProductName = "Sữa Tươi Vinamilk Có Đường 180ml",
                            SalePrice = 8500m,
                            Thumbnail = "https://images.unsplash.com/photo-1550583724-b2692b85b150",
                            Unit = "Hộp"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "8931112",
                            ImportPrice = 27000m,
                            ProductId = 2,
                            ProductName = "Lốc 4 Hộp Sữa Vinamilk 180ml",
                            SalePrice = 32000m,
                            Unit = "Lốc"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "8931113",
                            ImportPrice = 30000m,
                            ProductId = 2,
                            ProductName = "Sữa TH True Milk 1L",
                            SalePrice = 38000m,
                            Thumbnail = "https://images.unsplash.com/photo-1563636619-e9143da7973b",
                            Unit = "Hộp"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "8932221",
                            ImportPrice = 9000m,
                            ProductId = 3,
                            ProductName = "Coca Cola Lon 330ml",
                            SalePrice = 11000m,
                            Thumbnail = "https://images.unsplash.com/photo-1622483767028-3f66f32aef97",
                            Unit = "Lon"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "8932222",
                            ImportPrice = 18000m,
                            ProductId = 3,
                            ProductName = "Pepsi Chai 1.5L",
                            SalePrice = 22000m,
                            Thumbnail = "https://images.unsplash.com/photo-1629203851122-3726ecdf080e",
                            Unit = "Chai"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "8933331",
                            ImportPrice = 140000m,
                            ProductId = 4,
                            ProductName = "Dầu Gội Clear Men Bạc Hà 650g",
                            SalePrice = 165000m,
                            Thumbnail = "https://images.unsplash.com/photo-1631729371254-42c2a89ddf0d",
                            Unit = "Chai"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "8934441",
                            ImportPrice = 35000m,
                            ProductId = 5,
                            ProductName = "Nước Mắm Nam Ngư 750ml",
                            SalePrice = 42000m,
                            Unit = "Chai"
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PO-001",
                            CreatedById = 1,
                            OrderDate = new DateTime(2025, 12, 7, 15, 39, 30, 546, DateTimeKind.Utc).AddTicks(4338),
                            Status = "Received",
                            SupplierId = 4,
                            TotalAmount = 5000000m
                        },
                        new
                        {
                            Id = 2,
                            Code = "PO-002",
                            CreatedById = 1,
                            OrderDate = new DateTime(2025, 12, 7, 15, 39, 30, 546, DateTimeKind.Utc).AddTicks(4343),
                            Status = "Received",
                            SupplierId = 5,
                            TotalAmount = 8000000m
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.PurchaseOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDetailId = 1,
                            PurchaseOrderId = 1,
                            Quantity = 1000,
                            UnitPrice = 3500m
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDetailId = 3,
                            PurchaseOrderId = 1,
                            Quantity = 50,
                            UnitPrice = 100000m
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDetailId = 7,
                            PurchaseOrderId = 2,
                            Quantity = 500,
                            UnitPrice = 9000m
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cửa hàng trưởng",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thu ngân",
                            RoleName = "Cashier"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nhân viên kho",
                            RoleName = "InventoryStaff"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kế toán",
                            RoleName = "Accountant"
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId");

                    b.ToTable("SalesOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BILL-001",
                            CreatedById = 2,
                            CustomerId = 6,
                            OrderDate = new DateTime(2025, 12, 7, 15, 39, 30, 546, DateTimeKind.Utc).AddTicks(4397),
                            Status = "Completed",
                            TotalAmount = 15500m
                        },
                        new
                        {
                            Id = 2,
                            Code = "BILL-002",
                            CreatedById = 2,
                            CustomerId = 7,
                            OrderDate = new DateTime(2025, 12, 7, 15, 39, 30, 546, DateTimeKind.Utc).AddTicks(4401),
                            Status = "Completed",
                            TotalAmount = 125000m
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.SalesOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDetailId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 0m,
                            ProductDetailId = 1,
                            Quantity = 1,
                            SalesOrderId = 1,
                            UnitPrice = 4500m
                        },
                        new
                        {
                            Id = 2,
                            Discount = 0m,
                            ProductDetailId = 7,
                            Quantity = 1,
                            SalesOrderId = 1,
                            UnitPrice = 11000m
                        },
                        new
                        {
                            Id = 3,
                            Discount = 0m,
                            ProductDetailId = 3,
                            Quantity = 1,
                            SalesOrderId = 2,
                            UnitPrice = 125000m
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityChanged")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProductDetailId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedById = 2,
                            ProductDetailId = 1,
                            QuantityChanged = -1,
                            ReferenceCode = "BILL-001",
                            TransactionDate = new DateTime(2025, 12, 7, 15, 39, 30, 546, DateTimeKind.Utc).AddTicks(4446),
                            Type = "EXPORT",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedById = 2,
                            ProductDetailId = 7,
                            QuantityChanged = -1,
                            ReferenceCode = "BILL-001",
                            TransactionDate = new DateTime(2025, 12, 7, 15, 39, 30, 546, DateTimeKind.Utc).AddTicks(4449),
                            Type = "EXPORT",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedById = 2,
                            ProductDetailId = 3,
                            QuantityChanged = -1,
                            ReferenceCode = "BILL-002",
                            TransactionDate = new DateTime(2025, 12, 7, 15, 39, 30, 546, DateTimeKind.Utc).AddTicks(4451),
                            Type = "EXPORT",
                            WarehouseId = 1
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Quản Lý Cửa Hàng",
                            IsActive = true,
                            PasswordHash = "123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Em Thu Ngân Sáng",
                            IsActive = true,
                            PasswordHash = "123",
                            RoleId = 2,
                            Username = "thungan1"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Em Thu Ngân Chiều",
                            IsActive = true,
                            PasswordHash = "123",
                            RoleId = 2,
                            Username = "thungan2"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Anh Kho",
                            IsActive = true,
                            PasswordHash = "123",
                            RoleId = 3,
                            Username = "kho1"
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Kệ Trưng Bày",
                            Name = "Siêu Thị Mini Tầng 1"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Phòng Kho",
                            Name = "Kho Chứa Hàng Sau"
                        });
                });

            modelBuilder.Entity("Nexus.API.Models.InventoryStock", b =>
                {
                    b.HasOne("Nexus.API.Models.ProductDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Nexus.API.Models.Partner", b =>
                {
                    b.HasOne("Nexus.API.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("Nexus.API.Models.Payment", b =>
                {
                    b.HasOne("Nexus.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Nexus.API.Models.ProductDetail", b =>
                {
                    b.HasOne("Nexus.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Nexus.API.Models.PurchaseOrder", b =>
                {
                    b.HasOne("Nexus.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Models.Partner", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Nexus.API.Models.PurchaseOrderItem", b =>
                {
                    b.HasOne("Nexus.API.Models.ProductDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Nexus.API.Models.SalesOrder", b =>
                {
                    b.HasOne("Nexus.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Models.Partner", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Nexus.API.Models.SalesOrderItem", b =>
                {
                    b.HasOne("Nexus.API.Models.ProductDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Models.SalesOrder", "SalesOrder")
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Nexus.API.Models.StockTransaction", b =>
                {
                    b.HasOne("Nexus.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Models.ProductDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.API.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ProductDetail");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Nexus.API.Models.User", b =>
                {
                    b.HasOne("Nexus.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nexus.API.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Nexus.API.Models.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
